import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/molecules/navbar";

export const metadata: Metadata = {
  title: "Posts App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: IChildren) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
